name: Upload XoDos Release

on:
  workflow_dispatch:
    inputs:
      version_tag:
        description: 'Version tag (5.5.0)'
        required: true
        default: '5.5.0'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Git Tag
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git tag ${{ github.event.inputs.version_tag }}
          git push origin ${{ github.event.inputs.version_tag }}

      - name: Download Main APK
        run: |
          pip install gdown
          gdown "1-UjOF8B_7ZZyUTBR5VQJPjlzmjx74c5n" -O XoDos-${{ github.event.inputs.version_tag }}-full_arm64-v8a.apk || exit 1

      - name: Download Additional File
        run: |
          gdown "1--Nqu2iD7RdfLEsACqeGuc_75JHHSZOG" -O XoDos-debian-5.5.tar.xz || exit 1

      - name: Create Release with Both Files
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.version_tag }}
          name: XoDos ${{ github.event.inputs.version_tag }}
          files: |
            XoDos-${{ github.event.inputs.version_tag }}-full_arm64-v8a.apk
            XoDos-debian-5.5.tar.xz
          body: | 
            New XoDos release for arm64
            What's new?
            - 
            
            For best experience download the full version APK (1.7 GB) with Bionic and Glibc wine pre-installed
            
            **Credits:**
            Team: @xodiosx🇾🇪 & @DevArys🇨🇴 & @Mondo67244🇲🇫 & @Aurora0y🇧🇷 & @Chest1902🇧🇩 & @jiaxinchen-max 🇨🇳  & @Snap888🇷🇺
            Logo designer: @xl_v6/ashen🇮🇶
            
            **Support:**
            Telegram: https://t.me/xodemulatorr
            Discord: https://discord.gg/d2ChVhPfnF
            
            Thank you for choosing XoDos by xodios M.aleiw
